name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: building
      run: cargo build --verbose
    - name: testing
      run: cargo test --verbose
